name: Land-Plugin
version: '1.0'
main: io.hnewey.landplugin.LandPlugin
description: Land Plugin
api-version: '26.2'
author: hnewey
description: Land Plugin allows players to claim land through claim blocks which prevents other players from building on their land.

commands:
  land:
    description: Manages land plugin (e.g. getblock, add, remove, and delete)
    usage: /land <subcommand>
    permission: land.use

permissions:
  land.use:
    description: Allows players to use the land plugin.
    default: true